### ISSUE TITLE
BAHOZ - Users can be blocked from minting players from previous seasons

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-footium-judging#54]
BAHOZ

medium

# Users can be blocked from minting players from previous seasons

## Summary
Use of updatable `_maxGenerationId` may block some users from minting players from past seasons.

## Vulnerability Detail

`_maxGenerationId` is updatable via `changeMaxGenerationId()`:
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumAcademy.sol#L94-L97

This variable is used in `mintPlayers()` to limit the amount of mintable players:
https://github.com/sherlock-audit/2023-04-footium/blob/main/footium-eth-shareable/contracts/FootiumAcademy.sol#L186-L188

Since the check is made by the `generationId` instead of count of the minted players, this may cause certain users to be blocked from minting players from past seasons.

Consider this case:
`_maxGenerationId` = 10
`SeasonID` = 1
User Alice mints players with ids [0,1,2,3,4,5]
User Bob mints players with ids [6,7,8,9,10]

Next season comes:
Admin calls `changeMaxGenerationId(5)` and `changeCurrentSeasonId(2)`

`_maxGenerationId` = 5
`SeasonID` = 2

In this season Bob can mint 6 players from Season1 and 6 players from Season2, in total 12 players.
But Alice can only mint 6 players from Season2 and her mintable players from Season1 can not be minted anymore because the `_maxGenerationId` is used for all seasons and blocks legit Seasons1 mints

## Impact
May block some users from minting players. Medium Impact, Low probability.

## Code Snippet
PoC

```typescript
const generationIds = [0, 1, 2, 3, 4, 5, 6];
const ethAmount = ethers.BigNumber.from(divisionFees[0]).mul(
    generationIds.length
);

await expect(
    academy
        .connect(addr1)
        .mintPlayers(
            1,
            7,
            divisionTier,
            generationIds,
            clubDivProof,
            {
                value: ethAmount,
            }
        )
).to.not.reverted;
await academy.changeCurrentSeasonId(2);

await academy.changeMaxGenerationId(5);



await expect(
  academy
      .connect(addr1)
      .mintPlayers(
          1,
          7,
          divisionTier,
          [7, 8, 9, 10],
          clubDivProof,
          {
              value: ethAmount,
          }
      )
).to.not.reverted;
```

## Tool used

Manual Review

## Recommendation
Store how many players minted per team for each seasons, and check if thats bigger than the specific seasons maxMint count.

**Comment by 8ahoz** [comment]
Escalate for 10 USDC

I think this issue is valid and should be rewarded. Please explain why the issue is excluded.

The problem is not the admin configuration, admins are allowed to reduce maxGenerationId -and probably they will do that at some point since it makes sense to decrease mintable player count after some seasons to reduce player inflation.

The problem is when they do that, they will block some users from minting players from previous seasons unawarely.

lets consider this scenario:
assume Alice did not mint player with genId=8 and left that for next season
assume Bob did not mint player with genId=2 and left that for next season
although they did a similar thing leaving one player to mint later which should be possible by the specs, Alice will be blocked from minting her player in the second season but Bob can still mint his player.

I am open to discussion, but I think the issue here is severe enough to be considered as Medium because some users will lose their player NFTs.

Also, seeing #319 is accepted, makes my case stronger. Although I don't think they are dups, they have very similar impact and possibility. 

#319 causes minting more players from previous seasons when max gen id increased
#54 causes blocking mints from previous seasons when max gen id decreased

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I think this issue is valid and should be rewarded. Please explain why the issue is excluded.
> 
> The problem is not the admin configuration, admins are allowed to reduce maxGenerationId -and probably they will do that at some point since it makes sense to decrease mintable player count after some seasons to reduce player inflation.
> 
> The problem is when they do that, they will block some users from minting players from previous seasons unawarely.
> 
> lets consider this scenario:
> assume Alice did not mint player with genId=8 and left that for next season
> assume Bob did not mint player with genId=2 and left that for next season
> although they did a similar thing leaving one player to mint later which should be possible by the specs, Alice will be blocked from minting her player in the second season but Bob can still mint his player.
> 
> I am open to discussion, but I think the issue here is severe enough to be considered as Medium because some users will lose their player NFTs.
> 
> Also, seeing #319 is accepted, makes my case stronger. Although I don't think they are dups, they have very similar impact and possibility. 
> 
> #319 causes minting more players from previous seasons when max gen id increased
> #54 causes blocking mints from previous seasons when max gen id decreased
> 
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
Valid duplicate of https://github.com/sherlock-audit/2023-04-footium-judging/issues/319

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #319

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #319 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
